version: "3.8"
   
services:
  db_usuarios:
    container_name: db_usuarios
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api_usuarios:
    container_name: api_usuarios
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment: 
      - PUBLIC_JWT=AQUIDEBEIRLALLAVEPUBLICA
    depends_on:
      - db_usuarios